/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface-variant':        '#9eabc8',
        'on-primary-container':      '#ffffff',
        'on-primary':                '#2a0052',
        'error':                     '#ff716c',
        'tertiary-fixed-dim':        '#5eead4',
        'primary-container':         '#8b00ff',
        'surface-variant':           '#102645',
        'surface-dim':               '#010e24',
        'surface-tint':              '#b47cff',
        'surface':                   '#010e24',
        'surface-container-low':     '#02132b',
        'secondary-container':       '#241a4d',
        'tertiary-dim':              '#21d4bb',
        'tertiary':                  '#3ee8d2',
        'surface-bright':            '#152c4e',
        'on-secondary-container':    '#c0d0f7',
        'background':                '#010e24',
        'outline':                   '#687690',
        'on-surface':                '#dbe6ff',
        'secondary-fixed':           '#c4d4fb',
        'primary-dim':               '#a855f7',
        'surface-container-lowest':  '#010a1d',
        'primary-fixed-dim':         '#a855f7',
        'outline-variant':           '#3b4861',
        'on-secondary':              '#394969',
        'inverse-on-surface':        '#48556e',
        'primary':                   '#b47cff',
        'surface-container-high':    '#0b203d',
        'error-container':           '#9f0519',
        'inverse-primary':           '#6d00c7',
        'surface-container-highest': '#102645',
        'on-background':             '#dbe6ff',
        'secondary':                 '#c4d4fb',
        'tertiary-container':        '#0d9488',
        'surface-container':         '#061934',
        'primary-fixed':             '#b47cff',
        'inverse-surface':           '#f9f9ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:     '0.5rem',
        xl:     '0.75rem',
        '2xl':  '1rem',
        '3xl':  '1.5rem',
        full:   '9999px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      keyframes: {
        barPulse: {
          '0%, 100%': { transform: 'scaleY(0.3)' },
          '50%':      { transform: 'scaleY(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%':      { transform: 'translateY(-12px)' },
        },
        pulseRing: {
          '0%':   { opacity: '0.8', transform: 'scale(1)' },
          '100%': { opacity: '0',   transform: 'scale(1.15)' },
        },
      },
      animation: {
        'bar-pulse': 'barPulse 1.4s ease-in-out infinite',
        'pulse-ring': 'pulseRing 2s ease-out infinite',
        'float': 'float 6s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
